command /lightning-sword:
    permission: lightning.sword
    permission message: &cYou do not have permission to do this!
    trigger:
        set {sword} to unbreakable iron sword named "&b&l&nLightning Sword"
        enchant {sword} with sharpness 10
        enchant {sword} with fire aspect 4
        give {sword} to player

on damage:
    if attacker's tool is {sword}:
        strike lightning effect at victim
